### ISSUE TITLE
default type "default" to "_doc" 

### ISSUE THREAD

**Issue by amareshb** [codingexplained/complete-guide-to-elasticsearch#1]
Can I update the default type  from **default** to **_doc** in this Github repo as told in the lecture while I am doing the course?

**Comment by ba0708** [comment]
Sorry for the late response; I got no notification of this issue. Yes, definitely go ahead and use `_doc` instead of `default`. I have just [updated the mapping type](https://github.com/codingexplained/complete-guide-to-elasticsearch/commit/fd731629ae5ca015cec11aca9630a2b7626c2046) in the repository.
