### ISSUE TITLE
An Advice for you :)

### ISSUE THREAD

**Issue by Chetan11-dev** [codingexplained/complete-guide-to-elasticsearch#17]
See I am giving you advice for your benefit as a teacher..
I watched your course on ElasticSearch.

You say you will update the application and then you express your inability that of not doing it.It gives a bad impression on me as a student.
What you should do instead.
You should say in beginning of the course that you will be using this version and ask be to use that version via docker so i do not experience any incompatibility. 
---
This is a pattern which popular teacher like Mosh Hamedani does when he taught his course on docker (https://codewithmosh.com/p/the-ultimate-docker-course). He knew things can change so he explicity asks me to use the same version. 
---
Action Step you should take is:
Say explicitly I am will be using v7 of elastic search and make me install it via docker compose.

**Comment by ba0708** [comment]
Hi @Chetan11-dev and thank you for the feedback!

The reason I haven't done that is that the course is not locked to a specific version. Actually the course is from 2015 and has continually been updated to match newer versions, fix deprecations, etc. Since the course is so long, I work my way through it one section at a time, and so the queries are not updated all at the same time.

Unless specified otherwise, the course will always refer to the latest version of Elasticsearch, and it will be explicitly stated if any content is not up to date.

I am working on a new course update, so sorry for the inconvenience until then! 🙂

**Comment by Chetan11-dev** [comment]
Firstly Thank you for making the course it was informational.
But Well I do not even see the need for you to update the course it feels good to me? 
Don't you think you should spend your efforts in making new courses on other topics such as docker with that you will also have more revenue and help more people.

**Comment by ba0708** [comment]
From a business perspective, you are definitely right. The thing is that teaching is not my main occupation, and so I am not in it for the money. I am not really focused on revenue, which is also why I don't plan to publish any new courses in the foreseeable future. 🙂  Otherwise you would be absolutely right.

**Comment by Chetan11-dev** [comment]
You would be able to help thousands of people via teaching. Nevertheless Good Luck for the future. Bye :)
